---
title: 'Working Paper: Discrete Choice Analysis on Household Preferences'
author: "Kristopher C. Toll"
date: "December 13, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(mlogit, readr)
```



```{r include=FALSE}
logitdata2 <- read.csv(file = "I:/Utah Travel Study/Utah Travel Study/modified_data/logitdata2.csv")
```



```{r, include=FALSE}
# Model with only city observations
res1 <- mlogit::mlogit(choice ~1| commute + destinations + homes + streets + transit + ParkingDriveway  + ParkingOffStreet + NominalPrice + alt + chid,
                       data = subset(logitdata2, place_type_city_a == "1"), shape = "long", alt.var = "alt", id = "id", chid.var = "chid")


# Model with only suburban observations
res2 <- mlogit::mlogit(choice ~1| commute + destinations + homes + streets + transit + ParkingDriveway  + ParkingOffStreet + NominalPrice + alt + chid,
                       data = subset(logitdata2, place_type_suburban_a == "1"), shape = "long", alt.var = "alt", id = "id", chid.var = "chid")

# Model with only small town/Rural observations
res3 <- mlogit::mlogit(choice ~1| commute + destinations + homes + streets + transit + ParkingDriveway  + ParkingOffStreet + NominalPrice + alt + chid,
                       data = subset(logitdata2, place_type_SmallTownRural_a == "1"), shape = "long", alt.var = "alt", id = "id", chid.var = "chid")


# The Goodness of fit will be determined by either the Waldtest, lrtest or scoretest as soon as I figure out how to run them
# The same goes for heteroskedasticity



```


## Model with City observations

```{r model with city observations}
summary(res1)
```

## Model with Suburban Observations

```{r model with suburban observations}
summary(res2)
```

## Model with Small town/Rural Observations

```{r model with small town/Rural observations}
summary(res3)
```

# ASDF